sudo: required
dist: trusty

language: node_js

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

install:
  - docker-compose build

script:
  - docker-compose up

after_success:
  - cat $TRAVIS_BUILD_DIR/out/download.sh
  - ls -al $TRAVIS_BUILD_DIR/out/*
  - rm -rf $TRAVIS_BUILD_DIR/out
